### ISSUE TITLE
Working together!

### ISSUE THREAD

**Issue by wp2333** [MitchellX/deepfake-models#1]
Hey,
Happy to see someone interested in these projects of deepfakes.Recently,I'm trying to re-implement the job of FSGAN,but I get in some trouble.Would you like to send me an Email so that we can help each other about any possible problems?
Best wishes!

**Comment by MitchellX** [comment]
I've successfully installed the FSGAN. if you have any questions, you can send me an e-mail. 
you can find my e-mail address on my Github page.

**Comment by MitchellX** [comment]
> Hey,
> Happy to see someone interested in these projects of deepfakes.Recently,I'm trying to re-implement the job of FSGAN,but I get in some trouble.Would you like to send me an Email so that we can help each other about any possible problems?
> It's my Email:[wp123@mail.ustc.edu.cn](mailto:wp123@mail.ustc.edu.cn)
> Best wishes!

I've successfully installed the FSGAN. if you have any questions, you can send me an e-mail.
you can find my e-mail address on my Github page.

**Comment by MitchellX** [comment]
@wp2333 
I've successfully installed the FSGAN. if you have any questions, you can send me an e-mail.
you can find my e-mail address on my Github page.

**Comment by yBeOne** [comment]
Have you re-implement the job of FaceShifter?

**Comment by MitchellX** [comment]
@huanghanmei There are at least three un-official versions of FaceShifter on GitHub. So I just borrow from them, instead of re-implementing it by myself.

**Comment by yBeOne** [comment]
Do you have the pre_trained model?
