### ISSUE TITLE
"ours" column in the image

### ISSUE THREAD

**Issue by piemkay** [MitchellX/deepfake-models#2]
Hey, can you please let me know what the "ours" column refers to in the [image](https://github.com/MitchellX/deepfake-models/blob/main/image_results/celeba_re.png)?

**Comment by MitchellX** [comment]
It's our unpublished work on CVPR'2021.

**Comment by shorelake** [comment]
looking forward to your publication~

**Comment by johndpope** [comment]
Save the date

```
2021 Conference on Computer Vision and Pattern Recognition will begin on
Saturday, 19 June
and ends on
Friday, 25 June

```
Could you update this post when code is released? Thanks in advance.

**Comment by leonardodora** [comment]
great job! I believe your paper got accepted!
is there any plan to release the codes?

**Comment by MitchellX** [comment]
Unfortunately, it's not. We're considering switching to ICCV or ACM MM.
We'll update the post when the code is released.

**Comment by MitchellX** [comment]
@johndpope @shorelake @pkern90 @leonardodora 
The paper is published in ACM MM 2021. **One-stage Context and Identity Hallucination Network**

**Comment by piemkay** [comment]
First of all congratulation.
Are guys still planning on releasing the code? If so do you have an ETA?
