### ISSUE TITLE
what's the name of "our" work

### ISSUE THREAD

**Issue by molo32** [MitchellX/deepfake-models#3]
What is our work called?
give me the github link

**Comment by MitchellX** [comment]
sorry, it's our unpublished work, not yet open in Github. 
#2

**Comment by amil-rp-work** [comment]
@MitchellX  Hey I am really astonished by your work!
Great job indeed 👍 
Are you planning to release your work soon?

**Comment by MitchellX** [comment]
I'll update the post when the code is released.

**Comment by molo32** [comment]
any news of when the code will be published?

**Comment by MitchellX** [comment]
@amil-rp-work @molo32 
The paper is published in ACM MM 2021. **One-stage Context and Identity Hallucination Network**
