### ISSUE TITLE
where is 'our' paper?

### ISSUE THREAD

**Issue by Dian-Yi** [MitchellX/deepfake-models#4]

**Comment by molo32** [comment]
any news of when the code will be published?

**Comment by SystemErrorWang** [comment]
Would like to known if the above mentioned paper is published?

**Comment by Dian-Yi** [comment]
> Would like to known if the above mentioned paper is published?

yes, my gays

**Comment by SystemErrorWang** [comment]
> > Would like to known if the above mentioned paper is published?
> 
> yes, my gays

Would be grateful if you can tell me the title

**Comment by MitchellX** [comment]
@Dian-Yi @molo32 @SystemErrorWang 
The paper is published in ACM MM 2021. **One-stage Context and Identity Hallucination Network**

**Comment by johndpope** [comment]
Cool - https://dl.acm.org/doi/pdf/10.1145/3474085.347525

Well done.
<img width="606" alt="Screen Shot 2021-10-27 at 10 37 09 am" src="https://user-images.githubusercontent.com/289994/138976001-92e51dbf-74db-4dcc-8120-eb36ebab7edd.png">
7

**Comment by molo32** [comment]
when will you release the code?
