### ISSUE TITLE
when will you release the code cihaNet?

### ISSUE THREAD

**Issue by molo32** [MitchellX/deepfake-models#6]

**Comment by MitchellX** [comment]
It's hard to open the source code since it's company work.
Maybe you guys can ask the corresponding author for more information.

**Comment by loboere** [comment]
How do I contact the author / s?

**Comment by johndpope** [comment]
also - is there a link to commercial website to enquire.... rates + costs.

**Comment by loboere** [comment]
@johndpope  what is the site? can you share the link

**Comment by MitchellX** [comment]
the paper includes contact information
[[One-stage Context and Identity Hallucination Network
](https://dl.acm.org/doi/abs/10.1145/3474085.3475257)](https://dl.acm.org/doi/abs/10.1145/3474085.3475257)
